version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing build dependencies"

  build:
    commands:
      - echo "Zipping Lambda functions"

      - cd lambdas

      - zip -r producer.zip producer/app.py
      - zip -r consumer.zip consumer/app.py
      - zip -r replay.zip replay/app.py
      - zip -r backfill.zip backfill/app.py

      - cd ..

artifacts:
  files:
    - lambdas/producer.zip
    - lambdas/consumer.zip
    - lambdas/replay.zip
    - lambdas/backfill.zip
    - glue/raw_to_curated.py
